import Link from "next/link";
import { ArrowRight, BookOpenCheck, CalendarDays, CircleHelp, FileDown, MessageCircle } from "lucide-react";

const guides = [
  { title: "Manage appointments", description: "Create appointments, update their status, and send reminders from the appointment details page.", href: "/dashboard/appointments", icon: CalendarDays },
  { title: "Follow up with patients", description: "Use the Follow-ups centre to see overdue bookings and send upcoming WhatsApp reminders.", href: "/dashboard/follow-ups", icon: MessageCircle },
  { title: "Review and export data", description: "Use Reports for clinic performance, then download CSV files from Exports when you need them.", href: "/dashboard/reports", icon: FileDown },
];

export default function HelpPage() {
  return <div className="mx-auto max-w-5xl space-y-6"><header className="rounded-2xl border border-border bg-card px-6 py-7 shadow-sm sm:px-8"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary">DentalAI guide</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Help & quick start</h1><p className="mt-2 max-w-2xl text-muted-foreground">A short guide to the main daily workflows in your clinic workspace.</p></header><section className="grid gap-5 md:grid-cols-3">{guides.map(({ title, description, href, icon: Icon }) => <Link key={title} href={href} className="group rounded-2xl border border-border bg-card p-6 shadow-sm transition hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-md"><div className="grid size-11 place-items-center rounded-xl bg-cyan-50 text-cyan-700"><Icon className="size-5" /></div><h2 className="mt-5 text-lg font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p><span className="mt-6 inline-flex items-center gap-1 text-sm font-semibold text-primary">Open section <ArrowRight className="size-4 transition group-hover:translate-x-1" /></span></Link>)}</section><section className="flex gap-4 rounded-2xl border border-blue-100 bg-blue-50/60 p-5 text-sm text-blue-950"><BookOpenCheck className="mt-0.5 size-5 shrink-0 text-blue-700" /><div><p className="font-semibold">WhatsApp language selection</p><p className="mt-1 text-blue-900/80">When a new patient sends Hi, Hello, Menu, or Start, DentalAI first asks them to choose English, Hindi, or Marathi.</p></div></section><section className="flex gap-4 rounded-2xl border border-border bg-card p-5 text-sm"><CircleHelp className="mt-0.5 size-5 shrink-0 text-primary" /><p className="leading-6 text-muted-foreground">If an action does not work, check your internet connection and WhatsApp settings, then try again. The new error screen will always provide a safe retry option.</p></section></div>;
}
