"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

type Values = { fullName: string; phone: string; email?: string | null; dateOfBirth?: string | null; gender?: string | null; address?: string | null; medicalNotes?: string | null };
export default function PatientForm({ patient, mode = "create" }: { patient?: Values & { id: number }; mode?: "create" | "edit" }) {
  const router = useRouter(); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); const form = new FormData(event.currentTarget); const data = Object.fromEntries(form.entries()); try { const response = await fetch(mode === "create" ? "/api/patients" : `/api/patients/${patient?.id}`, { method: mode === "create" ? "POST" : "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); toast.success(mode === "create" ? "Patient added." : "Patient updated."); router.push(mode === "create" ? "/dashboard/patients" : `/dashboard/patients/${patient?.id}`); router.refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "Failed to save patient."); } finally { setLoading(false); } }
  return <form onSubmit={submit} className="space-y-6"><div className="grid gap-5 md:grid-cols-2"><label className="space-y-2 text-sm font-medium">Full name<Input required name="fullName" defaultValue={patient?.fullName} placeholder="Patient name" /></label><label className="space-y-2 text-sm font-medium">Phone number<Input required name="phone" defaultValue={patient?.phone} placeholder="10-digit mobile number" /></label><label className="space-y-2 text-sm font-medium">Email<Input name="email" type="email" defaultValue={patient?.email ?? ""} placeholder="name@example.com" /></label><label className="space-y-2 text-sm font-medium">Date of birth<Input name="dateOfBirth" type="date" defaultValue={patient?.dateOfBirth?.slice(0, 10) ?? ""} /></label><label className="space-y-2 text-sm font-medium">Gender<select name="gender" defaultValue={patient?.gender ?? ""} className="h-9 w-full rounded-md border bg-background px-3 text-sm"><option value="">Not specified</option><option>Female</option><option>Male</option><option>Non-binary</option><option>Prefer not to say</option></select></label><label className="space-y-2 text-sm font-medium">Address<Input name="address" defaultValue={patient?.address ?? ""} placeholder="Address" /></label></div><label className="block space-y-2 text-sm font-medium">Medical notes<Textarea name="medicalNotes" rows={5} defaultValue={patient?.medicalNotes ?? ""} placeholder="Allergies, conditions, or other notes…" /></label><div className="flex justify-end gap-3 border-t pt-5"><Button type="button" variant="outline" onClick={() => router.back()} disabled={loading}>Cancel</Button><Button disabled={loading}>{loading ? "Saving…" : mode === "create" ? "Add patient" : "Save changes"}</Button></div></form>;
}
