export const dynamic = "force-dynamic";

import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import PaymentForm from "@/components/billing/PaymentForm";

export default async function InvoicePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const invoice = await prisma.invoice.findUnique({ where: { id: Number(id) }, include: { patient: true, treatmentPlan: true, payments: { orderBy: { paidAt: "desc" } } } });
  if (!invoice) notFound();
  const paid = invoice.payments.reduce((sum, payment) => sum + payment.amount, 0); const outstanding = invoice.totalAmount - paid;
  return <div className="mx-auto max-w-4xl space-y-6"><div className="flex items-end justify-between"><div><Link href="/dashboard/billing" className="text-sm text-primary hover:underline">← Billing</Link><h1 className="mt-2 text-3xl font-bold">{invoice.invoiceNumber}</h1><p className="mt-1 text-muted-foreground">Invoice for <Link className="text-primary hover:underline" href={`/dashboard/patients/${invoice.patientId}`}>{invoice.patient.fullName}</Link></p></div><p className="rounded-full bg-muted px-3 py-1 text-sm font-medium">{invoice.status}</p></div><div className="grid gap-4 sm:grid-cols-3"><Card><CardContent className="pt-5"><p className="text-sm text-muted-foreground">Total</p><p className="text-2xl font-bold">₹{invoice.totalAmount.toLocaleString("en-IN")}</p></CardContent></Card><Card><CardContent className="pt-5"><p className="text-sm text-muted-foreground">Paid</p><p className="text-2xl font-bold text-emerald-700">₹{paid.toLocaleString("en-IN")}</p></CardContent></Card><Card><CardContent className="pt-5"><p className="text-sm text-muted-foreground">Outstanding</p><p className="text-2xl font-bold text-amber-700">₹{outstanding.toLocaleString("en-IN")}</p></CardContent></Card></div><div className="grid gap-6 md:grid-cols-2"><Card><CardHeader><CardTitle>Invoice details</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p><span className="text-muted-foreground">Issued:</span> {invoice.issueDate.toLocaleDateString()}</p><p><span className="text-muted-foreground">Due:</span> {invoice.dueDate?.toLocaleDateString() || "Not set"}</p><p><span className="text-muted-foreground">Treatment plan:</span> {invoice.treatmentPlan?.title || "Not linked"}</p><p className="whitespace-pre-wrap"><span className="text-muted-foreground">Notes:</span> {invoice.notes || "None"}</p></CardContent></Card><Card><CardHeader><CardTitle>Record payment</CardTitle></CardHeader><CardContent><PaymentForm invoiceId={invoice.id} outstanding={outstanding} /></CardContent></Card></div><Card><CardHeader><CardTitle>Payment history</CardTitle></CardHeader><CardContent>{invoice.payments.length === 0 ? <p className="py-5 text-sm text-muted-foreground">No payments recorded.</p> : <div className="divide-y">{invoice.payments.map((payment) => <div key={payment.id} className="flex justify-between py-3 text-sm"><div><p className="font-medium">{payment.method}</p><p className="text-muted-foreground">{payment.paidAt.toLocaleDateString()}{payment.notes ? ` · ${payment.notes}` : ""}</p></div><p className="font-semibold text-emerald-700">₹{payment.amount.toLocaleString("en-IN")}</p></div>)}</div>}</CardContent></Card></div>;
}
