import Link from "next/link";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requireUser } from "@/lib/auth";
import { createStaffAction, toggleStaffAction, updateClinicAction } from "./actions";

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const user = await requireUser();
  if (user.role !== "OWNER") redirect("/dashboard");
  const { error } = await searchParams;
  const staff = await prisma.user.findMany({ where: { clinicId: user.clinicId }, orderBy: [{ role: "asc" }, { fullName: "asc" }] });
  return <div className="mx-auto max-w-5xl space-y-6">
    <div><p className="text-sm font-bold uppercase tracking-[0.16em] text-sky-700">Premium setup</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Clinic settings & staff access</h1><p className="mt-2 text-muted-foreground">Only the clinic owner can manage clinic details and staff accounts.</p></div>
    {error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">Could not add staff. Check the email is unused and the password has at least 10 characters.</p>}
    <section className="rounded-2xl border bg-card p-6 shadow-sm"><h2 className="text-xl font-bold">Clinic operations</h2><p className="mt-1 text-sm text-muted-foreground">Configure services, working hours, booking slots and WhatsApp wording without touching code.</p><Link href="/dashboard/settings/operations" className="mt-4 inline-flex rounded-xl bg-sky-700 px-5 py-2.5 text-sm font-semibold text-white hover:bg-sky-800">Manage clinic operations</Link></section>
    <section className="rounded-2xl border bg-card p-6 shadow-sm"><h2 className="text-xl font-bold">Production launch</h2><p className="mt-1 text-sm text-muted-foreground">Review environment setup, WhatsApp readiness, staff handover, and the production checklist before giving access to a clinic.</p><Link href="/dashboard/launch" className="mt-4 inline-flex rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-semibold text-white hover:bg-slate-700">Open launch centre</Link></section>
    <section className="rounded-2xl border bg-card p-6 shadow-sm"><h2 className="text-xl font-bold">Clinic profile</h2><form action={updateClinicAction} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Clinic name<input name="name" required defaultValue={user.clinic.name} className="mt-1.5 h-11 w-full rounded-xl border px-3 font-normal" /></label><label className="text-sm font-semibold">Clinic phone<input name="phone" defaultValue={user.clinic.phone ?? ""} className="mt-1.5 h-11 w-full rounded-xl border px-3 font-normal" /></label><label className="text-sm font-semibold">Clinic email<input name="email" type="email" defaultValue={user.clinic.email ?? ""} className="mt-1.5 h-11 w-full rounded-xl border px-3 font-normal" /></label><label className="text-sm font-semibold">Clinic address<input name="address" defaultValue={user.clinic.address ?? ""} className="mt-1.5 h-11 w-full rounded-xl border px-3 font-normal" /></label><button className="h-11 w-fit rounded-xl bg-sky-700 px-5 font-semibold text-white hover:bg-sky-800">Save clinic profile</button></form></section>
    <section className="rounded-2xl border bg-card p-6 shadow-sm"><h2 className="text-xl font-bold">Add staff member</h2><form action={createStaffAction} className="mt-5 grid gap-4 md:grid-cols-2"><input name="fullName" required placeholder="Full name" className="h-11 rounded-xl border px-3" /><input name="email" type="email" required placeholder="Staff email" className="h-11 rounded-xl border px-3" /><input name="password" type="password" minLength={10} required placeholder="Temporary password (10+ characters)" className="h-11 rounded-xl border px-3" /><select name="role" defaultValue="RECEPTIONIST" className="h-11 rounded-xl border bg-white px-3"><option value="RECEPTIONIST">Receptionist</option><option value="DENTIST">Dentist</option></select><button className="h-11 w-fit rounded-xl bg-slate-900 px-5 font-semibold text-white hover:bg-slate-700">Add staff login</button></form></section>
    <section className="rounded-2xl border bg-card p-6 shadow-sm"><h2 className="text-xl font-bold">Current access</h2><div className="mt-4 divide-y">{staff.map((member) => <div key={member.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="font-semibold">{member.fullName} <span className="ml-2 rounded-full bg-slate-100 px-2 py-1 text-xs text-slate-600">{member.role}</span></p><p className="text-sm text-muted-foreground">{member.email} · {member.active ? "Active" : "Disabled"}</p></div>{member.id !== user.id && <form action={toggleStaffAction}><input type="hidden" name="userId" value={member.id} /><input type="hidden" name="active" value={String(!member.active)} /><button className="rounded-xl border px-4 py-2 text-sm font-semibold hover:bg-muted">{member.active ? "Disable" : "Enable"}</button></form>}</div>)}</div></section>
  </div>;
}
