"use client";

import { useMemo, useState } from "react";
import { saveDentalChartEntryAction } from "@/app/dashboard/clinical-workspace/actions";

type Entry = { toothNumber: string; condition: string; notes: string | null };
const teeth = ["18", "17", "16", "15", "14", "13", "12", "11", "21", "22", "23", "24", "25", "26", "27", "28", "48", "47", "46", "45", "44", "43", "42", "41", "31", "32", "33", "34", "35", "36", "37", "38"];
const labels: Record<string, string> = { HEALTHY: "Healthy", CARIES: "Caries", FILLING: "Filling", CROWN: "Crown", ROOT_CANAL: "Root canal", MISSING: "Missing", IMPLANT: "Implant", WATCH: "Watch" };
const styles: Record<string, string> = { HEALTHY: "border-emerald-200 bg-emerald-50 text-emerald-800", CARIES: "border-rose-200 bg-rose-50 text-rose-800", FILLING: "border-sky-200 bg-sky-50 text-sky-800", CROWN: "border-violet-200 bg-violet-50 text-violet-800", ROOT_CANAL: "border-amber-200 bg-amber-50 text-amber-900", MISSING: "border-slate-200 bg-slate-100 text-slate-600", IMPLANT: "border-cyan-200 bg-cyan-50 text-cyan-800", WATCH: "border-orange-200 bg-orange-50 text-orange-800" };

export default function DentalChartEditor({ patientId, entries }: { patientId: number; entries: Entry[] }) {
  const [selected, setSelected] = useState("18");
  const byTooth = useMemo(() => new Map(entries.map((entry) => [entry.toothNumber, entry])), [entries]);
  const selectedEntry = byTooth.get(selected);
  return <div className="grid gap-6 lg:grid-cols-[1.4fr_0.8fr]"><section className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Dental chart</h2><p className="mt-1 text-sm text-muted-foreground">Select a tooth to document its current clinical condition.</p></div><div className="flex flex-wrap gap-2 text-xs">{["HEALTHY", "CARIES", "FILLING", "CROWN", "ROOT_CANAL", "MISSING", "IMPLANT", "WATCH"].map((condition) => <span key={condition} className={`rounded-full border px-2 py-1 ${styles[condition]}`}>{labels[condition]}</span>)}</div></div><div className="mt-8 grid gap-3"><div className="grid grid-cols-8 gap-2">{teeth.slice(0, 16).map((tooth) => <Tooth key={tooth} tooth={tooth} selected={selected === tooth} condition={byTooth.get(tooth)?.condition} onSelect={setSelected} />)}</div><div className="h-px bg-border" /><div className="grid grid-cols-8 gap-2">{teeth.slice(16).map((tooth) => <Tooth key={tooth} tooth={tooth} selected={selected === tooth} condition={byTooth.get(tooth)?.condition} onSelect={setSelected} />)}</div></div></section><aside className="rounded-2xl border border-border bg-card p-6 shadow-sm"><h2 className="text-lg font-bold">Tooth {selected}</h2><p className="mt-1 text-sm text-muted-foreground">Update the chart entry for this tooth.</p><form action={saveDentalChartEntryAction} className="mt-6 space-y-4"><input type="hidden" name="patientId" value={patientId} /><input type="hidden" name="toothNumber" value={selected} /><label className="block text-sm font-medium">Condition<select key={`${selected}-${selectedEntry?.condition || "HEALTHY"}`} name="condition" defaultValue={selectedEntry?.condition || "HEALTHY"} className="mt-2 h-11 w-full rounded-xl border bg-card px-3">{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="block text-sm font-medium">Clinical note<textarea key={`${selected}-${selectedEntry?.notes || ""}`} name="notes" defaultValue={selectedEntry?.notes || ""} rows={5} placeholder="Finding, material, advice, or planned treatment" className="mt-2 w-full rounded-xl border bg-card p-3 text-sm" /></label><button className="h-11 w-full rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground transition hover:opacity-90">Save tooth entry</button></form></aside></div>;
}

function Tooth({ tooth, selected, condition = "HEALTHY", onSelect }: { tooth: string; selected: boolean; condition?: string; onSelect: (tooth: string) => void }) {
  return <button type="button" onClick={() => onSelect(tooth)} className={`aspect-square rounded-xl border p-1 text-xs font-bold transition hover:scale-105 ${styles[condition] || styles.HEALTHY} ${selected ? "ring-2 ring-primary ring-offset-2" : ""}`}><span className="block text-[10px] opacity-70">{tooth}</span><span className="mt-1 block truncate text-[9px]">{condition === "HEALTHY" ? "" : labels[condition]}</span></button>;
}
