"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
type Patient = { id: number; fullName: string; phone: string };
export default function TreatmentPlanForm({ patients }: { patients: Patient[] }) { const router = useRouter(); const [saving, setSaving] = useState(false); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); try { const response = await fetch("/api/treatment-plans", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget).entries())) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); toast.success("Treatment plan saved."); router.push(`/dashboard/patients/${body.patientId}`); router.refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not save treatment plan."); } finally { setSaving(false); } } return <form onSubmit={submit} className="space-y-6"><div className="grid gap-5 md:grid-cols-2"><label className="space-y-2 text-sm font-medium">Patient<select required name="patientId" className="h-9 w-full rounded-md border bg-background px-3"><option value="">Select patient</option>{patients.map((patient) => <option key={patient.id} value={patient.id}>{patient.fullName} - {patient.phone}</option>)}</select></label><label className="space-y-2 text-sm font-medium">Plan title<Input required name="title" placeholder="e.g. Full mouth rehabilitation" /></label><label className="space-y-2 text-sm font-medium">Status<select name="status" defaultValue="Proposed" className="h-9 w-full rounded-md border bg-background px-3"><option>Proposed</option><option>Accepted</option><option>In Progress</option><option>Completed</option><option>Cancelled</option></select></label><label className="space-y-2 text-sm font-medium">Estimated cost (INR)<Input name="estimatedCost" type="number" min="0" placeholder="0" /></label></div><label className="block space-y-2 text-sm font-medium">Plan notes<Textarea name="notes" rows={6} placeholder="Planned procedures, timeline, patient instructions" /></label><div className="flex justify-end gap-3 border-t pt-5"><Button type="button" variant="outline" onClick={() => router.back()}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? "Saving..." : "Save treatment plan"}</Button></div></form>; }
