export const dynamic = "force-dynamic";

import { BarChart3, CircleCheckBig, CircleX, Plus, UserRoundPlus } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { requireUser } from "@/lib/auth";
import { saveLeadAction, updateLeadAction } from "./actions";

const stages = ["NEW", "CONTACTED", "BOOKED", "VISITED", "CONVERTED", "LOST"];
const stageStyles: Record<string, string> = { NEW: "bg-sky-100 text-sky-800", CONTACTED: "bg-violet-100 text-violet-800", BOOKED: "bg-amber-100 text-amber-800", VISITED: "bg-blue-100 text-blue-800", CONVERTED: "bg-emerald-100 text-emerald-800", LOST: "bg-rose-100 text-rose-800" };

export default async function LeadsPage() {
  const user = await requireUser();
  const leads = await prisma.lead.findMany({ where: { clinicId: user.clinicId }, include: { activities: { orderBy: { createdAt: "desc" }, take: 1 } }, orderBy: { updatedAt: "desc" }, take: 150 });
  const count = (stage: string) => leads.filter((lead) => lead.stage === stage).length;
  const converted = count("CONVERTED");
  const conversionRate = leads.length ? Math.round((converted / leads.length) * 100) : 0;
  const cards = [{ label: "New enquiries", value: count("NEW"), icon: UserRoundPlus, tone: "bg-sky-50 text-sky-700" }, { label: "Booked", value: count("BOOKED"), icon: CircleCheckBig, tone: "bg-amber-50 text-amber-700" }, { label: "Converted", value: converted, icon: BarChart3, tone: "bg-emerald-50 text-emerald-700" }, { label: "Lost", value: count("LOST"), icon: CircleX, tone: "bg-rose-50 text-rose-700" }];
  return <div className="mx-auto max-w-7xl space-y-6">
    <header><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary">AI conversion coach</p><h1 className="mt-1 text-3xl font-bold tracking-tight sm:text-4xl">Lead CRM</h1><p className="mt-2 text-muted-foreground">Capture enquiries, move them through the booking journey, and learn why leads are lost.</p></header>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, icon: Icon, tone }) => <article key={label} className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm font-medium text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div><div className={`grid size-10 place-items-center rounded-xl ${tone}`}><Icon className="size-5" /></div></div></article>)}</section>
    <section className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Conversion health</h2><p className="mt-1 text-sm text-muted-foreground">{conversionRate}% of all saved enquiries are marked converted.</p></div><span className="rounded-xl bg-emerald-50 px-4 py-2 text-xl font-bold text-emerald-700">{conversionRate}%</span></div></section>
    <section className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex items-center gap-2"><Plus className="size-5 text-primary" /><h2 className="text-lg font-bold">Add enquiry</h2></div><form action={saveLeadAction} className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><input name="fullName" required placeholder="Patient name" className="h-11 rounded-xl border px-3" /><input name="phone" required placeholder="10-digit mobile number" className="h-11 rounded-xl border px-3" /><input name="email" type="email" placeholder="Email (optional)" className="h-11 rounded-xl border px-3" /><input name="serviceInterest" placeholder="Interested service" className="h-11 rounded-xl border px-3" /><select name="source" defaultValue="Manual" className="h-11 rounded-xl border bg-card px-3"><option>Manual</option><option>WhatsApp</option><option>Website</option><option>Google</option><option>Referral</option><option>Walk-in</option></select><input name="notes" placeholder="Enquiry note" className="h-11 rounded-xl border px-3" /><button className="h-11 rounded-xl bg-primary px-5 font-semibold text-primary-foreground hover:opacity-90">Save enquiry</button></form></section>
    <section className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div className="border-b border-border px-6 py-5"><h2 className="text-lg font-bold">Lead pipeline</h2><p className="mt-1 text-sm text-muted-foreground">Update the stage after each call, WhatsApp reply or visit.</p></div>{leads.length === 0 ? <div className="px-6 py-12 text-center text-sm text-muted-foreground">No leads yet. Add an enquiry above.</div> : <div className="divide-y divide-border">{leads.map((lead) => <article key={lead.id} className="p-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{lead.fullName}</p><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${stageStyles[lead.stage]}`}>{lead.stage}</span></div><p className="mt-1 text-sm text-muted-foreground">{lead.phone} · {lead.source}{lead.serviceInterest ? ` · ${lead.serviceInterest}` : ""}</p><p className="mt-2 text-sm">{lead.notes || "No notes added."}</p><p className="mt-2 text-xs text-muted-foreground">Last activity: {lead.activities[0]?.content || "No activity"}</p></div><form action={updateLeadAction} className="grid min-w-0 gap-2 sm:grid-cols-2 xl:w-[430px]"><input type="hidden" name="id" value={lead.id} /><select name="stage" defaultValue={lead.stage} className="h-10 rounded-lg border bg-card px-3 text-sm">{stages.map((stage) => <option key={stage} value={stage}>{stage}</option>)}</select><input name="nextFollowUpAt" type="datetime-local" defaultValue={lead.nextFollowUpAt ? lead.nextFollowUpAt.toISOString().slice(0, 16) : ""} className="h-10 rounded-lg border px-3 text-sm" /><input name="lossReason" defaultValue={lead.lossReason || ""} placeholder="Loss reason (if lost)" className="h-10 rounded-lg border px-3 text-sm" /><input name="notes" defaultValue={lead.notes || ""} placeholder="Update note" className="h-10 rounded-lg border px-3 text-sm" /><button className="h-10 rounded-lg bg-slate-900 px-4 text-sm font-semibold text-white hover:bg-slate-700 sm:col-span-2">Update lead</button></form></div></article>)}</div>}</section>
  </div>;
}
