export const dynamic = "force-dynamic";

import { AlertTriangle, FlaskConical, PackageCheck, Plus, Truck } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { addInventoryItemAction, addLabCaseAction, adjustInventoryAction, updateLabCaseAction } from "./actions";

const statuses = ["SENT_TO_LAB", "IN_PROGRESS", "READY", "DELIVERED", "CANCELLED"];
const statusStyles: Record<string, string> = { SENT_TO_LAB: "bg-sky-100 text-sky-800", IN_PROGRESS: "bg-amber-100 text-amber-800", READY: "bg-emerald-100 text-emerald-800", DELIVERED: "bg-violet-100 text-violet-800", CANCELLED: "bg-rose-100 text-rose-800" };

export default async function OperationsPage() {
  const user = await requireUser();
  const [items, labCases, patients, treatmentPlans] = await Promise.all([
    prisma.inventoryItem.findMany({ where: { clinicId: user.clinicId, active: true }, orderBy: [{ quantity: "asc" }, { name: "asc" }] }),
    prisma.labCase.findMany({ where: { clinicId: user.clinicId }, include: { patient: true }, orderBy: [{ dueDate: "asc" }, { updatedAt: "desc" }], take: 100 }),
    prisma.patient.findMany({ select: { id: true, fullName: true, phone: true }, orderBy: { fullName: "asc" } }),
    prisma.treatmentPlan.findMany({ select: { id: true, patientId: true, title: true }, orderBy: { updatedAt: "desc" }, take: 200 }),
  ]);
  const lowStock = items.filter((item) => item.quantity <= item.reorderLevel);
  const openLab = labCases.filter((item) => !["DELIVERED", "CANCELLED"].includes(item.status));
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const overdueLab = openLab.filter((item) => item.dueDate && item.dueDate < today);
  const cards = [{ label: "Inventory items", value: items.length, icon: PackageCheck, tone: "bg-cyan-50 text-cyan-700" }, { label: "Low stock", value: lowStock.length, icon: AlertTriangle, tone: "bg-amber-50 text-amber-800" }, { label: "Open lab cases", value: openLab.length, icon: FlaskConical, tone: "bg-violet-50 text-violet-700" }, { label: "Lab cases overdue", value: overdueLab.length, icon: Truck, tone: "bg-rose-50 text-rose-700" }];
  return <div className="mx-auto max-w-7xl space-y-6"><header><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary">Clinic operations</p><h1 className="mt-1 text-3xl font-bold tracking-tight sm:text-4xl">Inventory & lab workflow</h1><p className="mt-2 text-muted-foreground">Track essential clinical supplies and every outside-lab case from dispatch to delivery.</p></header><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, icon: Icon, tone }) => <article key={label} className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm font-medium text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div><div className={`grid size-10 place-items-center rounded-xl ${tone}`}><Icon className="size-5" /></div></div></article>)}</section>
    <section className="grid gap-5 xl:grid-cols-2"><article className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex items-center gap-2"><Plus className="size-5 text-primary" /><h2 className="text-lg font-bold">Add or update inventory</h2></div><form action={addInventoryItemAction} className="mt-5 grid gap-3 sm:grid-cols-2"><input name="name" required placeholder="Item name" className="h-11 rounded-xl border px-3" /><input name="category" placeholder="Category" className="h-11 rounded-xl border px-3" /><input name="quantity" type="number" min="0" defaultValue="0" placeholder="Current quantity" className="h-11 rounded-xl border px-3" /><input name="reorderLevel" type="number" min="0" defaultValue="0" placeholder="Reorder level" className="h-11 rounded-xl border px-3" /><input name="unit" defaultValue="units" placeholder="Unit" className="h-11 rounded-xl border px-3" /><input name="costPerUnit" type="number" min="0" placeholder="Cost per unit (Rs.)" className="h-11 rounded-xl border px-3" /><button className="h-11 rounded-xl bg-primary px-4 font-semibold text-primary-foreground sm:col-span-2">Save inventory item</button></form></article><article className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex items-center gap-2"><FlaskConical className="size-5 text-primary" /><h2 className="text-lg font-bold">Create lab case</h2></div><form action={addLabCaseAction} className="mt-5 grid gap-3 sm:grid-cols-2"><select required name="patientId" className="h-11 rounded-xl border bg-card px-3"><option value="">Select patient</option>{patients.map((patient) => <option key={patient.id} value={patient.id}>{patient.fullName} — {patient.phone}</option>)}</select><select name="treatmentPlanId" className="h-11 rounded-xl border bg-card px-3"><option value="">Treatment plan (optional)</option>{treatmentPlans.map((plan) => <option key={plan.id} value={plan.id}>{plan.title}</option>)}</select><input required name="labName" placeholder="Lab name" className="h-11 rounded-xl border px-3" /><input required name="caseType" placeholder="Case type (crown, aligner...)" className="h-11 rounded-xl border px-3" /><input name="dueDate" type="date" className="h-11 rounded-xl border px-3" /><input name="notes" placeholder="Instructions / shade / notes" className="h-11 rounded-xl border px-3" /><button className="h-11 rounded-xl bg-primary px-4 font-semibold text-primary-foreground sm:col-span-2">Create lab case</button></form></article></section>
    <section className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div className="border-b border-border px-6 py-5"><h2 className="text-lg font-bold">Stock levels</h2><p className="mt-1 text-sm text-muted-foreground">Items at or below their reorder level are highlighted.</p></div>{items.length === 0 ? <div className="px-6 py-12 text-center text-sm text-muted-foreground">No inventory items added yet.</div> : <div className="divide-y divide-border">{items.map((item) => <article key={item.id} className="flex flex-col gap-4 px-6 py-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{item.name}</p>{item.quantity <= item.reorderLevel && <span className="rounded-full bg-amber-100 px-2.5 py-1 text-xs font-bold text-amber-800">Reorder</span>}</div><p className="mt-1 text-sm text-muted-foreground">{item.category} · {item.quantity} {item.unit} available · reorder at {item.reorderLevel}</p></div><form action={adjustInventoryAction} className="flex items-center gap-2"><input type="hidden" name="id" value={item.id} /><input name="adjustment" type="number" required placeholder="+ / - quantity" className="h-10 w-36 rounded-xl border px-3 text-sm" /><button className="h-10 rounded-xl border border-border bg-card px-4 text-sm font-semibold hover:bg-muted">Adjust</button></form></article>)}</div>}</section>
    <section className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div className="border-b border-border px-6 py-5"><h2 className="text-lg font-bold">Lab cases</h2><p className="mt-1 text-sm text-muted-foreground">Update status as the lab receives, completes, and returns each case.</p></div>{labCases.length === 0 ? <div className="px-6 py-12 text-center text-sm text-muted-foreground">No lab cases created yet.</div> : <div className="divide-y divide-border">{labCases.map((labCase) => <article key={labCase.id} className="flex flex-col gap-4 px-6 py-5 xl:flex-row xl:items-center xl:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{labCase.caseType}</p><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${statusStyles[labCase.status]}`}>{labCase.status.replaceAll("_", " ")}</span></div><p className="mt-1 text-sm text-muted-foreground">{labCase.patient.fullName} · {labCase.labName}{labCase.dueDate ? ` · Due ${labCase.dueDate.toLocaleDateString("en-IN")}` : ""}</p>{labCase.notes && <p className="mt-2 text-sm">{labCase.notes}</p>}</div><form action={updateLabCaseAction} className="flex gap-2"><input type="hidden" name="id" value={labCase.id} /><select name="status" defaultValue={labCase.status} className="h-10 rounded-xl border bg-card px-3 text-sm">{statuses.map((status) => <option key={status} value={status}>{status.replaceAll("_", " ")}</option>)}</select><button className="h-10 rounded-xl bg-slate-900 px-4 text-sm font-semibold text-white hover:bg-slate-700">Update</button></form></article>)}</div>}</section></div>;
}
